#!/usr/bin/env node
'use strict';

/**
 * JARVIS Setup Wizard
 * Run: node scripts/setup.js
 */

const readline = require('readline');
const fs       = require('fs');
const path     = require('path');
const { exec } = require('child_process');

const chalk = require('chalk');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((res) => rl.question(q, res));

async function main() {
  console.clear();
  console.log(chalk.cyan(`
╔══════════════════════════════════════════╗
║      JARVIS AI - First Time Setup        ║
╚══════════════════════════════════════════╝
`));

  // 1. Groq API Key
  console.log(chalk.yellow('Step 1: Groq API Key'));
  console.log(chalk.gray('  Get your free key from: https://console.groq.com'));
  const apiKey = await ask(chalk.white('  Enter your Groq API Key: '));

  // 2. Model selection
  console.log(chalk.yellow('\nStep 2: AI Model'));
  console.log(chalk.gray('  1. llama3-70b-8192    (Recommended - Best quality)'));
  console.log(chalk.gray('  2. llama3-8b-8192     (Faster, lighter)'));
  console.log(chalk.gray('  3. mixtral-8x7b-32768 (Large context window)'));
  const modelChoice = await ask(chalk.white('  Choose model [1-3, default 1]: '));
  const models = {
    '1': 'llama3-70b-8192',
    '2': 'llama3-8b-8192',
    '3': 'mixtral-8x7b-32768'
  };
  const model = models[modelChoice.trim()] || 'llama3-70b-8192';

  // 3. Voice mode
  const voiceChoice = await ask(chalk.white('\nStep 3: Enable voice mode? (requires microphone) [y/N]: '));
  const voiceMode = voiceChoice.trim().toLowerCase() === 'y';

  // 4. Auto-start
  const autoStart = await ask(chalk.white('\nStep 4: Auto-start Jarvis on Windows boot? [y/N]: '));
  const autoStartEnabled = autoStart.trim().toLowerCase() === 'y';

  // 5. Wake word
  let wakeWord = 'jarvis';
  if (voiceMode) {
    const wakeInput = await ask(chalk.white('\nStep 5: Wake word [default: jarvis]: '));
    wakeWord = wakeInput.trim() || 'jarvis';
  }

  // 6. Chrome path
  console.log(chalk.yellow('\nStep 6: Chrome Path'));
  const defaultChrome = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
  const chromeInput = await ask(chalk.white(`  Chrome exe path [default: ${defaultChrome}]: `));
  const chromePath  = chromeInput.trim() || defaultChrome;

  // Write .env file
  const envContent = `# JARVIS AI CONFIGURATION
# Generated by setup wizard on ${new Date().toLocaleString()}

GROQ_API_KEY=${apiKey.trim()}
GROQ_MODEL=${model}
ASSISTANT_NAME=Jarvis
DEBUG_MODE=false
VOICE_MODE=${voiceMode}
SILENT_MODE=false
AUTO_START=${autoStartEnabled}
HISTORY_LIMIT=100
SCREENSHOT_ENABLED=true
LANGUAGE=en
WAKE_WORD=${wakeWord}
MEMORY_DB_PATH=./memory/jarvis_memory.json
LOGS_PATH=./logs/
SCHEDULER_ENABLED=true
MAX_RETRIES=3
CHROME_PATH=${chromePath}
`;

  const envPath = path.resolve('.env');
  fs.writeFileSync(envPath, envContent, 'utf8');
  console.log(chalk.green('\n  ✓ .env file created'));

  // Create required directories
  ['memory', 'logs', 'plugins'].forEach(dir => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
      console.log(chalk.green(`  ✓ Created /${dir} directory`));
    }
  });

  // Install dependencies
  console.log(chalk.yellow('\n  Installing dependencies...'));
  console.log(chalk.gray('  This may take a few minutes...\n'));

  await new Promise((resolve) => {
    const install = exec('npm install', { cwd: path.resolve('.') });
    install.stdout.on('data', d => process.stdout.write(chalk.gray(d)));
    install.stderr.on('data', d => process.stdout.write(chalk.gray(d)));
    install.on('close', resolve);
  });

  // Auto-start setup
  if (autoStartEnabled) {
    console.log(chalk.yellow('\n  Setting up Windows auto-start...'));
    const jarvisPath = path.resolve('index.js');
    const nodeExe    = process.execPath;
    const regCmd     = `reg add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run" /v "JarvisAI" /t REG_SZ /d "\\"${nodeExe}\\" \\"${jarvisPath}\\"" /f`;
    exec(regCmd, (err) => {
      if (err) {
        console.log(chalk.red('  ✗ Auto-start setup failed. Run as administrator if needed.'));
      } else {
        console.log(chalk.green('  ✓ Auto-start registered in Windows Registry'));
      }
    });
  }

  rl.close();

  console.log(chalk.cyan(`
╔══════════════════════════════════════════╗
║         Setup Complete!                  ║
║                                          ║
║  Run Jarvis:  node index.js              ║
║  Debug mode:  node index.js --debug      ║
╚══════════════════════════════════════════╝
`));
}

main().catch(console.error);
